services:
  memgpt_server:
    container_name: MEMGPT
    image: vandracon/thaumaturgy/memgpt:1.0.0
    hostname: memgpt-server
    env_file:
      - ./local/instance/memgpt/.env
    environment:
      - MEMGPT_SERVER_PASS=password
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./local/instance/memgpt:/root/.memgpt
    ports:
      - "8083:8083"
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "touch /root/.memgpt/sqlite.db && test -f /root/.memgpt/sqlite.db && test -s /root/.memgpt/sqlite.db",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  thaumaturgy:
    container_name: THAUMATURGY
    depends_on:
      memgpt_server:
        condition: service_healthy
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    image: vandracon/thaumaturgy:1.0.0
    volumes:
      - ./config:/app/config
      - ./local/instance/thaumaturgy/thaumaturgy.db:/app/local/thaumaturgy.db
      - ./local/instance/thaumaturgy/thaumaturgydebug.db:/app/local/thaumaturgydebug.db
      - ./local/instance/memgpt/sqlite.db:/app/local/sqlite.db
      - ./local/instance/memgpt/config:/app/local/config
      - ./data:/app/local/data
    environment:
      - NODE_ENV=production
      - MEMGPT_SQLITE_DATABASE_PATH=/app/local/sqlite.db
      - MEMGPT_CONFIG_PATH=/app/local/config
      - MEMGPT_BASE_URL=http://MEMGPT:8083
      - LLM_ENDPOINT=http://host.docker.internal:5001/v1/chat/completions
      - CHARACTERS_CSV_PATH=local/data/skyrim_characters.csv
    ports:
      - "8050:8050"
